disabled_rules:
 - line_length
 - nesting
included:
    - Sources
identifier_name:
    excluded:
        - id
        - EmptyLeaf
        - _isFinished
        - _isExecuting
        - NoCodingPartBody
        - NoCodingPart

