included:
    - Sources
line_length: 180
identifier_name:
    excluded:
        - id
        - EmptyLeaf
        - _isFinished
        - _isExecuting
        - NoCodingPartBody
        - NoCodingPart

